<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()) { ?>
    <?php $siteId = Mage::getStoreConfig(RespondrMage_RespondrAnalytics_Helper_Data::XML_PATH_SITE); ?>
    <?php $installPath = Mage::getStoreConfig(RespondrMage_RespondrAnalytics_Helper_Data::SERVER_URL) ?>
    <?php if ($siteId) { ?>
        <!-- RESPONDR TRACKING CODE -->
        <script type="text/javascript">
            var _raq = _raq || [];
            (function () {
                _raq.push(['trackSession', '<?php echo $siteId ?>']);
                <!--?php $this->_saveContact(); ?-->
                <?php $this->_trackPageView(); ?>
                <!--?php $this->_trackCategoryView(); ?-->
                <!--?php $this->_trackProductView(); ?-->
                <?php $this->_trackCartAdds(); ?>
                <?php $this->_trackCartUpdates(); ?>
                <?php $this->_trackCartDeletes(); ?>
                <!--?php $this->_trackOrder(); ?-->
                <!--?php $this->_trackSiteSearch(); ?-->
                var u = (('https:' == document.location.protocol) ? 'https://analytics.respondr.io/' : 'http://analytics.respondr.io/');
                u = 'http://localhost:1338/';
                var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
                g.type = 'text/javascript';
                g.defer = true;
                g.async = true;
                g.src = u + 'static/respondr.js';
                s.parentNode.insertBefore(g, s);
            })();
        </script>
        <!-- END RESPONDR TRACKING CODE -->
    <?php } ?>
<?php } ?>
