<?php
/**
 *
 * Respondr Extension for Magento created by Respondr Inc.
 * Based on Piwik Extension for Magento by Adrian Speyer
 *
 * @category   RespondrMage
 * @package    RespondrMage_RespondrAnalytics
 * @copyright  Copyright (c) 2014 Respondr Inc. (http://www.respondr.io)
 * @license    http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 */
?>
<?php $siteId = Mage::getStoreConfig(RespondrMage_RespondrAnalytics_Helper_Data::XML_PATH_SITE) ?>

<!-- RESPONDR TRACKING CODE --> 
<script type="text/javascript">
//<![CDATA[
<?php if ($siteId) { ?>	
  var _raq = _raq || [];
  _raq.push(["trackSession", "<?php echo $siteId ?>"]);
  (function() {
      var u=(("https:" == document.location.protocol) ? "https" : "http") + "://analytics.respondr.io/static/";
      var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
      g.defer=true; g.async=true; g.src=u+"respondr.js"; s.parentNode.insertBefore(g,s);
  })();
<?php echo $this->_getPageview()?>
<?php echo $this->_getEcommerceCartUpdate()?>
<?php echo $this->_getOrdersTrackingCode()?>
<?php echo $this->_getUser()?>
<?php } ?>
//]]>
</script>
